package main

//migrate to https://github.com/eurie-inc/echo-sample
//https://github.com/pangpanglabs/echosample
//https://github.com/kyawmyintthein/golangRestfulAPISample

import (
	"go-webapp/config"
	"go-webapp/module/server"
	"go-webapp/routes"
	"runtime"

	log "github.com/sirupsen/logrus"

	"github.com/gin-gonic/gin"

	_ "go-webapp/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {

	// Only log the warning severity or above.
	log.SetLevel(log.DebugLevel)
}

/**
* run main.go(go run main.go) and visit 0.0.0.0:8080/ping on browser
 */

func main() {

	// Set maximum number of CPUs that can be executing simultaneously with the number of logical CPUs usable by the current process
	runtime.GOMAXPROCS(runtime.NumCPU())

	//TODO Enable GZIP

	if config.GetEnv().DEBUG {
		gin.SetMode(gin.DebugMode)
	} else {
		gin.SetMode(gin.ReleaseMode)
	}

	router := routes.InitRouter() // 初始化路由

	server.Run(router)

}
