// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-05-15 14:06:39.157500078 +0530 IST m=+0.050089475

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "API Base .",
        "title": "API Documentation",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:4000",
    "basePath": "/api",
    "paths": {
        "/v1/register": {
            "post": {
                "description": "Register an account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add a new user",
                "parameters": [
                    {
                        "description": "username",
                        "name": "username",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
										{
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
										{
                        "description": "first name",
                        "name": "first_name",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
										{
                        "description": "last name",
                        "name": "last_name",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
										{
                        "description": "phone",
                        "name": "phone",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
										{
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },

                }
            }
        },

    },

}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
